apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.fileName }}
  namespace: {{ .Release.Namespace }}
  labels:
    env: {{ .Values.global.env }}
    platform: {{ .Values.global.platform }}
    appid: {{ .Values.global.appid }}
    lob: {{ .Values.global.lob }}
data:
  {{ .Values.configMap.fileName }}: |-
    {{ .Values.cert.certstring | quote }}
