apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: {{ .Values.HorizontalRunnerAutoscaler.name }}
  #namespace: {{ .Values.global.namespace }}
  namespace: {{ .Release.Namespace }}
  labels:
    env: {{ .Values.global.env }}
    platform: {{ .Values.global.platform }}
    appid: {{ .Values.global.appid }}
    lob: {{ .Values.global.lob }}
spec:
  scaleDownDelaySecondsAfterScaleOut: {{ .Values.HorizontalRunnerAutoscaler.specs.scaleDownDelaySecondsAfterScaleOut }}
  minReplicas: {{ .Values.HorizontalRunnerAutoscaler.specs.minReplicas }}
  maxReplicas: {{ .Values.HorizontalRunnerAutoscaler.specs.maxReplicas }}
  scaleTargetRef:
    name: {{ .Values.HorizontalRunnerAutoscaler.specs.scaleTargetRefName }}
    # Uncomment the below in case the target is not RunnerDeployment but RunnerSet
    #kind: RunnerSet
  scaleUpTriggers:
  - githubEvent:
      workflowJob: {}
    duration: {{ .Values.HorizontalRunnerAutoscaler.specs.github_event_duration }}

