apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: runners-HorizontalRunnerAutoscaler
  namespace: actions-runner-system
spec:
  scaleDownDelaySecondsAfterScaleOut: 300
  minReplicas: 4
  maxReplicas: 10
  scaleTargetRef:
    name: org-runnerdeploy
    # Uncomment the below in case the target is not RunnerDeployment but RunnerSet
    #kind: RunnerSet
  scaleUpTriggers:
  - githubEvent:
      workflowJob: {}
    duration: "30m"
