apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: org-runnerdeploy
  namespace: actions-runner-system
spec:
  replicas: 2 
  template:
    spec:
      organization: GitRunnerOrg
      
