apiVersion: v1
data:
  github_token: "Z2hwXzZlcGtSOFpWZ3MzdElSWE1SVVREQXY1eVlUUDFOVDJNVURwSw"
kind: Secret
metadata:
  creationTimestamp: null
  name: controller-manager
  namespace: actions-runner-system
