apiVersion: v1
kind: Secret
metadata:
  name: ecr-registry-helper-secrets
  namespace: actions-runner-system 
stringData:
  AWS_SECRET_ACCESS_KEY: {{ .Values.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: {{ .Values.AWS_ACCESS_KEY_ID }}
  AWS_ACCOUNT: {{ .Values.AWS_ACCOUNT }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ecr-registry-helper-cm
  namespace: action-runner-system
data:
  AWS_REGION: {{ .Values.AWS_REGION }}
  DOCKER_SECRET_NAME: regcred
