## Global values ##

global:
  namespace: actions-runner-system
  env: dev
  appid: example-123
  lob: example-lob
  platform: eks
## values for configMap

configMap:
  name: cyberarkcm
  fileName: wiz-cyberarkcm.pem

cert:
  certstring: |-
    -----BEGIN CERTIFICATE-----
    MIICyTCCAbTCEF+F3G/7tLCJj9mZ/RiaPQEwDQYJKoZIhvcNAQELBQAwIzEhMB8GA1UEAxMYc2FjLWh2bTAwODc5LnN3aW5mcmEubmV0MB4XDTE5MDkyMDEwMDk1NloXDTQ0MDkxMzEwMDk1NlowIzEhMB8GA1UEAxMYc2FjLWh2bTAwODc5LnN3aW5mcmEubmV0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtmBCXjv7/8pjzUyqO52/NAVgOpVAj+i4d1bMdFvfonUzZVzvTfmTxLoHVXAAYrivYq5Y9hpTVIxM0rWjAsomYfH3AEgGYax8YGSdF0LW0USEeXZiaMf+Z5+N43d8BoCdGOkPZZQEIMaQwnxMouLisTV113x0vzHZR7b1JzZyMF5zYw88Lsul+TEOfkpY0zjmoptFM26pYSkx8J87n0aTe1ZN7TFDZ3zu629BHYfcwvy2F/m0E6rnFRa7o4o6qXJSfZIe1kqqvbRc
    -----END CERTIFICATE-----

## values for the runner autoscaler### 
HorizontalRunnerAutoscaler:
  name: runnerautoscale
  specs:  
    minReplicas: 1
    maxReplicas: 2
    tgtCpuUtilization: 80
    tgtMemUtilization: 80
    scaleDownDelaySecondsAfterScaleOut: 300
    scaleTargetRefName: org-runnerdeploy
    github_event_duration: 30m
 
 ## values for the runner deployment### 
RunnerDeployment:
  name: org-runnerdeploy
  replicas: 2
  ghe_org: GitRunnerOrg
  #ghe_enterprise: 
  #ghe_repo: 
  runner_labels: ["dev", "non-prod"]
  runner_group: Default
  STARTUP_DELAY_IN_SECONDS: 20
  DISABLE_WAIT_FOR_DOCKER: true
  DISABLE_RUNNER_UPDATE: true
     
    
