## Global values ##

global:
  namespace: actions-runner-system
  env: dev
  deployEnv: dev
  appid: example-123
  lob: example-lob
  platform: eks
 
## values for the runner autoscaler### 
HorizontalRunnerAutoscaler:
  name: runnerautoscale
  specs:  
    minReplicas: 1
    maxReplicas: 2
    tgtCpuUtilization: 80
    tgtMemUtilization: 80
    scaleDownDelaySecondsAfterScaleOut: 300
    scaleTargetRefName: org-runnerdeploy
    github_event_duration: 30m
 
 ## values for the runner deployment### 
RunnerDeployment:
  name: org-runnerdeploy
  replicas: 2
  ghe_org: GitRunnerOrg
  #ghe_enterprise: 
  #ghe:repo: 
  runner_labels: 
    - dev
    - non-prod
  runner_group: Default
  STARTUP_DELAY_IN_SECONDS: "20"
  DISABLE_WAIT_FOR_DOCKER: "true"
  DISABLE_RUNNER_UPDATE: "true"
     
    
