apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: runner-autoscaler
  namespace: actions-runner-system
spec:
  minReplicas: 4
  maxReplicas: 10
  scaleTargetRef:
    name: org-runnerdeploy
  metrics:
    - type: PercentageRunnersBusy
      scaleUpThreshold: '1'
      scaleDownThreshold: '0.5'
      ScaleUpAdjustment: '1'
      ScaleDownAdjustment: '1'
  scaleUpTriggers:
    - githubEvent:
        checkRun:
          types:
            - created
          status: queued
      amount: 1
      duration: 5m
