apiVersion: v1
data:
  github_token: {{ .Values.githubWebhookServer.secret.github_token | toString | b64enc }}
kind: Secret
metadata:
  creationTimestamp: null
  name: controller-manager
  namespace: actions-runner-system
