name: Release Helm Charts
concurrency: release-helm
'on':
  workflow_dispatch: null
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: src
          fetch-depth: 0
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: dest
          ref: gh-pages
          fetch-depth: 0
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1
      - name: Package Helm Charts
        shell: bash
        run: >
          find src/charts/ -type f -name 'Chart.yaml' | sed -r 's|/[^/]+$||' |
          sort | uniq | xargs -L 1 helm dep up

          for d in src/charts/*/ ; do
              echo "$d"
              helm package "$d" -u -d dest/docs
          done
      - name: Push New Files
        shell: bash
        working-directory: dest/docs
        run: >
          helm repo index . --url
          https://raw.githubusercontent.com/GitRunnerOrg/runner-helm-charts-repo/gh-pages

          git config user.name "RjDev"

          git config user.email "rjdevnic@gmail.com"

          git add $(git ls-files -o --exclude-standard)

          git add index.yaml

          git commit -m "Updated from ref: $GITHUB_SHA"

          git push
